/** Apple design system — typography scale. */
export const typography = {
  heroDisplay: {
    fontFamily: '"SF Pro Display", system-ui, -apple-system, sans-serif',
    fontSize: '56px',
    fontWeight: 600,
    lineHeight: 1.07,
    letterSpacing: '-0.28px',
  },
  displayLg: {
    fontFamily: '"SF Pro Display", system-ui, -apple-system, sans-serif',
    fontSize: '40px',
    fontWeight: 600,
    lineHeight: 1.1,
    letterSpacing: '0',
  },
  displayMd: {
    fontFamily: '"SF Pro Text", system-ui, -apple-system, sans-serif',
    fontSize: '34px',
    fontWeight: 600,
    lineHeight: 1.47,
    letterSpacing: '-0.374px',
  },
  lead: {
    fontFamily: '"SF Pro Display", system-ui, -apple-system, sans-serif',
    fontSize: '28px',
    fontWeight: 400,
    lineHeight: 1.14,
    letterSpacing: '0.196px',
  },
  leadAiry: {
    fontFamily: '"SF Pro Text", system-ui, -apple-system, sans-serif',
    fontSize: '24px',
    fontWeight: 300,
    lineHeight: 1.5,
    letterSpacing: '0',
  },
  tagline: {
    fontFamily: '"SF Pro Display", system-ui, -apple-system, sans-serif',
    fontSize: '21px',
    fontWeight: 600,
    lineHeight: 1.19,
    letterSpacing: '0.231px',
  },
  bodyStrong: {
    fontFamily: '"SF Pro Text", system-ui, -apple-system, sans-serif',
    fontSize: '17px',
    fontWeight: 600,
    lineHeight: 1.24,
    letterSpacing: '-0.374px',
  },
  body: {
    fontFamily: '"SF Pro Text", system-ui, -apple-system, sans-serif',
    fontSize: '17px',
    fontWeight: 400,
    lineHeight: 1.47,
    letterSpacing: '-0.374px',
  },
  denseLink: {
    fontFamily: '"SF Pro Text", system-ui, -apple-system, sans-serif',
    fontSize: '17px',
    fontWeight: 400,
    lineHeight: 2.41,
    letterSpacing: '0',
  },
  caption: {
    fontFamily: '"SF Pro Text", system-ui, -apple-system, sans-serif',
    fontSize: '14px',
    fontWeight: 400,
    lineHeight: 1.43,
    letterSpacing: '-0.224px',
  },
  captionStrong: {
    fontFamily: '"SF Pro Text", system-ui, -apple-system, sans-serif',
    fontSize: '14px',
    fontWeight: 600,
    lineHeight: 1.29,
    letterSpacing: '-0.224px',
  },
  buttonLarge: {
    fontFamily: '"SF Pro Text", system-ui, -apple-system, sans-serif',
    fontSize: '18px',
    fontWeight: 300,
    lineHeight: 1.0,
    letterSpacing: '0',
  },
  buttonUtility: {
    fontFamily: '"SF Pro Text", system-ui, -apple-system, sans-serif',
    fontSize: '14px',
    fontWeight: 400,
    lineHeight: 1.29,
    letterSpacing: '-0.224px',
  },
  finePrint: {
    fontFamily: '"SF Pro Text", system-ui, -apple-system, sans-serif',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 1.0,
    letterSpacing: '-0.12px',
  },
  microLegal: {
    fontFamily: '"SF Pro Text", system-ui, -apple-system, sans-serif',
    fontSize: '10px',
    fontWeight: 400,
    lineHeight: 1.3,
    letterSpacing: '-0.08px',
  },
  navLink: {
    fontFamily: '"SF Pro Text", system-ui, -apple-system, sans-serif',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 1.0,
    letterSpacing: '-0.12px',
  },
} as const;
