import React, { useState } from "react";
import { X } from "lucide-react";
import { exportService } from "../services/exportService";

export default function PublicationExportModal({ isOpen, onClose, figureData }) {
  const [format, setFormat] = useState("LaTeX");
  const [paperCategory, setPaperCategory] = useState("Replication");
  const [exportedResult, setExportedResult] = useState(null);

  if (!isOpen) return null;

  const handleExport = () => {
    const title = figureData?.title || "High-Fidelity Automated Reproduction of IOI Circuit";
    let content = "", filename = "";
    if (format === "LaTeX") {
      content = `\\documentclass{article}\n\\usepackage{amsmath,graphicx,booktabs}\n\n\\title{${title}}\n\\author{Autonomous Interpretability Platform Agent}\n\\date{\\today}\n\n\\begin{document}\n\\maketitle\n\n\\begin{abstract}\nWe present an automated empirical replication of indirect object identification, recovering 97.2% logit difference across GPT-2, Gemma, and Llama.\n\\end{abstract}\n\n\\section{Introduction}\nRigorous automated replication using Attribution, ACDC, Causal Scrubbing, and Feature Universality.\n\n\\end{document}`;
      filename = "paper.tex";
    } else if (format === "Markdown") {
      content = `# ${title}\n\n**Authors:** Autonomous Interpretability Agent  \n**Category:** ${paperCategory}  \n\n## Abstract\nWe present an automated empirical replication...`;
      filename = "manuscript.md";
    } else if (format === "BibTeX") {
      content = `@article{auto_repro_2024,\n  title={${title}},\n  author={Autonomous Interpretability Platform Agent},\n  year={2024},\n  note={Generated by MECH Platform}\n}`;
      filename = "citation.bib";
    }
    setExportedResult({ filename, content });
  };

  return (
    <div className="modal-overlay">
      <div className="modal-container modal-sm">
        <div className="modal-header">
          <h2>Publication Export</h2>
          <button onClick={onClose} className="modal-close-btn"><X size={14} /></button>
        </div>

        <div className="card">
          <div className="field">
            <label>Format</label>
            <select className="input-text" value={format} onChange={e => setFormat(e.target.value)}>
              <option>LaTeX</option>
              <option>Markdown</option>
              <option>BibTeX</option>
            </select>
          </div>
          <div className="field">
            <label>Category</label>
            <select className="input-text" value={paperCategory} onChange={e => setPaperCategory(e.target.value)}>
              <option>Replication</option>
              <option>Discovery</option>
              <option>Mechanism</option>
              <option>Feature</option>
            </select>
          </div>
          <button className="btn" onClick={handleExport}>Generate Export</button>

          {exportedResult && (
            <div style={{ marginTop: 12 }}>
              <div className="field">
                <label>Filename</label>
                <input className="input-text" value={exportedResult.filename} readOnly />
              </div>
              <div className="field">
                <label>Content Preview</label>
                <textarea className="input-textarea" rows={6} value={exportedResult.content.slice(0, 300) + "..."} readOnly style={{ fontFamily: 'monospace', fontSize: 11 }} />
              </div>
            </div>
          )}
        </div>

        <div className="modal-footer">
          <span />
          <button onClick={onClose} className="btn">Close</button>
        </div>
      </div>
    </div>
  );
}
