import React, { useState } from 'react';
import { FileText, Save, Download, Trash2, RefreshCw } from 'lucide-react';
import { colors } from '../design/tokens/colors';
import { useModel } from '../shared/hooks/useModel';
import { useWorkspaceStore } from '../shared/stores/workspace';
import { ExperimentRun } from './ExperimentsView';

interface Report {
  id: string;
  title: string;
  createdAt: string;
  content: string;
}

const STORAGE = 'mech.reports';

const load = (): Report[] => {
  try {
    return JSON.parse(localStorage.getItem(STORAGE) ?? '[]') as Report[];
  } catch {
    return [];
  }
};

const loadRuns = (): ExperimentRun[] => {
  try {
    return JSON.parse(localStorage.getItem('mech.experiments') ?? '[]') as ExperimentRun[];
  } catch {
    return [];
  }
};

export const ReportsView: React.FC = () => {
  const { state: model } = useModel();
  const { console: consoleLogs, timeline, notes } = useWorkspaceStore();
  const [reports, setReports] = useState<Report[]>(load);
  const [draft, setDraft] = useState(() => buildDraft(now()));

  function now() {
    return new Date().toLocaleString();
  }

  function buildDraft(ts: string): string {
    const runs = loadRuns();
    const ok = runs.filter((r) => r.ok).length;
    const tokens = runs.reduce((a, r) => a + r.tokens, 0);
    const errs = consoleLogs.filter((l) => l.level === 'error').length;
    return [
      `# Progress Report — ${ts}`,
      '',
      `## Environment`,
      `- Model: ${model.modelInfo?.model_name ?? 'not loaded'}`,
      `- Layers/heads: ${model.modelInfo?.num_layers ?? '–'} / ${model.modelInfo?.num_heads ?? '–'}`,
      `- Workspace: (see Sessions)`,
      ``,
      `## Experiment summary`,
      `- Runs executed: ${runs.length}`,
      `- Successful: ${ok}${runs.length ? ` (${Math.round((ok / runs.length) * 100)}%)` : ''}`,
      `- Tokens generated: ${tokens}`,
      `- Console errors: ${errs}`,
      '',
      '## Recent activity',
      ...timeline.slice(-6).map((t) => `- ${t.ts} — ${t.event}`),
      '',
      `## Notes (${notes.length})`,
      ...notes.slice(0, 5).map((n) => `- ${n.title}: ${n.content}`),
      '',
      '_Generated by the Reports tool from live workspace state._',
    ].join('\n');
  }

  const regenerate = () => setDraft(prev => buildDraft(new Date().toLocaleString()));

  const save = () => {
    const r: Report = { id: `rep_${Date.now()}`, title: `Report ${new Date().toLocaleDateString()}`, createdAt: now(), content: draft };
    setReports([r, ...reports]);
    try {
      localStorage.setItem(STORAGE, JSON.stringify([r, ...reports]));
    } catch {
      void 0;
    }
  };

  const remove = (id: string) => {
    const next = reports.filter((r) => r.id !== id);
    setReports(next);
    try {
      localStorage.setItem(STORAGE, JSON.stringify(next));
    } catch {
      void 0;
    }
  };

  const exportMd = (r: Report) => {
    const blob = new Blob([r.content], { type: 'text/markdown' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${r.title.replace(/[^a-z0-9]+/gi, '-')}.md`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12, fontSize: 13, color: colors.body, padding: 4 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <FileText size={16} color={colors.primary} />
        <span style={{ fontWeight: 700, color: colors.ink, fontSize: 15 }}>Research Reports</span>
        <span style={{ marginLeft: 'auto', fontSize: 11, color: colors.bodyMuted }}>{reports.length} saved</span>
        <button onClick={regenerate} style={{ background: 'none', border: 'none', cursor: 'pointer', color: colors.bodyMuted, display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 11 }}>
          <RefreshCw size={12} /> Regenerate
        </button>
      </div>

      <div style={{ border: `1px solid ${colors.hairline}`, borderRadius: 8, background: colors.canvas, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
        <div style={{ fontWeight: 700, color: colors.ink }}>Draft report (derived from live state)</div>
        <pre style={{ margin: 0, whiteSpace: 'pre-wrap', fontFamily: 'monospace', fontSize: 11, color: colors.body, background: colors.canvasParchment, borderRadius: 6, padding: 10, maxHeight: 260, overflow: 'auto' }}>{draft}</pre>
        <button onClick={save} style={{ alignSelf: 'flex-start', background: colors.primary, color: colors.onPrimary, border: 'none', borderRadius: 6, padding: '6px 14px', fontSize: 12, fontWeight: 600, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: 6 }}>
          <Save size={13} /> Save report
        </button>
      </div>

      {reports.length === 0 && (
        <div style={{ fontSize: 12, color: colors.bodyMuted, border: `1px dashed ${colors.hairline}`, borderRadius: 8, padding: 16 }}>
          No reports saved yet. Generate a snapshot report from the current workspace state.
        </div>
      )}

      {reports.map((r) => (
        <div key={r.id} style={{ border: `1px solid ${colors.hairline}`, borderRadius: 8, background: colors.canvas, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ fontWeight: 700, color: colors.ink }}>{r.title}</span>
            <span style={{ fontSize: 11, color: colors.bodyMuted }}>{r.createdAt}</span>
            <span style={{ marginLeft: 'auto', display: 'flex', gap: 6 }}>
              <button onClick={() => exportMd(r)} style={{ background: 'none', border: 'none', color: colors.bodyMuted, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 11 }}>
                <Download size={12} /> .md
              </button>
              <button onClick={() => remove(r.id)} style={{ background: 'none', border: 'none', color: colors.dangerText, cursor: 'pointer', display: 'inline-flex', alignItems: 'center' }}>
                <Trash2 size={13} />
              </button>
            </span>
          </div>
          <pre style={{ margin: 0, whiteSpace: 'pre-wrap', fontFamily: 'monospace', fontSize: 11, color: colors.body, background: colors.canvasParchment, borderRadius: 6, padding: 10, maxHeight: 160, overflow: 'auto' }}>{r.content}</pre>
        </div>
      ))}
    </div>
  );
};
