"""Archive Manifest Builder and Standalone Reproduction Script Generator.

Generates self-contained, hash-verified research archives for any MECH experiment run.
"""

from __future__ import annotations

import hashlib
import json
import os
import zipfile
from io import BytesIO
from pathlib import Path
from typing import Any, Dict, Tuple

from .types import ImmutableExperimentRun


def _hash_str(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def generate_standalone_reproduce_script(run: ImmutableExperimentRun) -> str:
    """Generates a standalone Python reproduction script that executes outside MECH."""
    spec = run.specification
    model = run.model
    meas = run.measurements

    return f'''"""Standalone Reproduction Script for MECH Experiment '{run.run_id}'.

Generated by MECH Platform (Phase 11 Reproducibility Engine).
Run with: python reproduce.py
"""

import json
import sys
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

EXPECTED_RESULTS = {{
    "clean_logit": {meas.get("clean_logit", 0.0)},
    "intervened_logit": {meas.get("intervened_logit", 0.0)},
    "delta_logit": {meas.get("delta_logit", 0.0)},
    "clean_rank": {meas.get("clean_rank", 0)},
    "intervened_rank": {meas.get("intervened_rank", 0)},
    "clean_probability": {meas.get("clean_probability", 0.0)},
    "intervened_probability": {meas.get("intervened_probability", 0.0)},
}}

SPECIFICATION = {{
    "model_id": "{model.model_id}",
    "clean_prompt": "{spec.clean_prompt}",
    "target_token": "{spec.target_token}",
    "layer": {spec.layer},
    "component_type": "{spec.component_type}",
    "component_index": {spec.component_index},
    "ablation_scale": {spec.ablation_scale},
    "random_seed": {spec.random_seed},
}}

def main():
    print("=" * 70)
    print(f"MECH REPRODUCTION AUDIT: {{SPECIFICATION['model_id']}} on '{{SPECIFICATION['clean_prompt']}}'")
    print("=" * 70)

    torch.manual_seed(SPECIFICATION["random_seed"])
    print(f"1. Loading model '{{SPECIFICATION['model_id']}}'...")
    tokenizer = AutoTokenizer.from_pretrained(SPECIFICATION["model_id"])
    model = AutoModelForCausalLM.from_pretrained(SPECIFICATION["model_id"])
    model.eval()

    # Verify target token
    target_ids = tokenizer.encode(SPECIFICATION["target_token"])
    target_id = target_ids[-1]
    print(f"2. Target token: '{{SPECIFICATION['target_token']}}' (ID: {{target_id}})")

    # 3. Clean Run
    inputs = tokenizer(SPECIFICATION["clean_prompt"], return_tensors="pt")
    with torch.no_grad():
        clean_out = model(**inputs)
    clean_logits = clean_out.logits[0, -1]
    clean_target_logit = float(clean_logits[target_id].item())
    clean_probs = torch.softmax(clean_logits, dim=-1)
    clean_target_prob = float(clean_probs[target_id].item())
    clean_rank = int((clean_logits > clean_target_logit).sum().item())

    print(f"3. Clean Run: Logit={{clean_target_logit:.4f}}, Prob={{clean_target_prob:.4f}}, Rank={{clean_rank}}")

    # 4. Forward hook intervention
    layer_idx = SPECIFICATION["layer"]
    neuron_idx = SPECIFICATION["component_index"]
    scale = SPECIFICATION["ablation_scale"]

    def hook_fn(module, input, output):
        # Zero/scale ablate component
        if isinstance(output, tuple):
            act = output[0].clone()
            if act.shape[-1] > neuron_idx:
                act[:, :, neuron_idx] *= scale
            return (act,) + output[1:]
        act = output.clone()
        if act.shape[-1] > neuron_idx:
            act[:, :, neuron_idx] *= scale
        return act

    hook_handle = None
    if hasattr(model, "transformer") and hasattr(model.transformer, "h"):
        target_layer = model.transformer.h[layer_idx].mlp.c_fc
        hook_handle = target_layer.register_forward_hook(hook_fn)

    try:
        with torch.no_grad():
            intervened_out = model(**inputs)
    finally:
        if hook_handle:
            hook_handle.remove()

    intervened_logits = intervened_out.logits[0, -1]
    intervened_target_logit = float(intervened_logits[target_id].item())
    intervened_probs = torch.softmax(intervened_logits, dim=-1)
    intervened_target_prob = float(intervened_probs[target_id].item())
    intervened_rank = int((intervened_logits > intervened_target_logit).sum().item())
    delta_logit = clean_target_logit - intervened_target_logit

    print(f"4. Intervened: Logit={{intervened_target_logit:.4f}}, Prob={{intervened_target_prob:.4f}}, Rank={{intervened_rank}}")
    print(f"5. Measured Causal Delta z: {{delta_logit:.4f}}")

    # 5. Assertions within numerical tolerance (abs <= 1e-3)
    diff = abs(delta_logit - EXPECTED_RESULTS["delta_logit"])
    print("-" * 70)
    print(f"TOLERANCE CHECK: |delta_obs - delta_exp| = {{diff:.2e}}")
    if diff <= 1e-3:
        print(">> VERDICT: REPRODUCED SUCCESSFULLY WITHIN NUMERICAL TOLERANCE <<")
        sys.exit(0)
    else:
        print(">> VERDICT: NUMERICAL DIVERGENCE DETECTED <<")
        sys.exit(1)

if __name__ == "__main__":
    main()
'''


def generate_readme_md(run: ImmutableExperimentRun) -> str:
    """Generates the README for the reproducibility archive."""
    spec = run.specification
    model = run.model
    env = run.environment
    prov = run.provenance_chain
    meas = run.measurements

    return rf"""# MECH Scientific Experiment Archive
**Run ID**: `{run.run_id}`  
**Experiment Type**: `{run.experiment_type}`  
**Generated At (UTC)**: `{run.timestamp_utc}`  
**Manifest Hash**: `{run.manifest_sha256}`  

---

## 1. Specification
- **Clean Prompt**: `{spec.clean_prompt}`
- **Target Token**: `{spec.target_token}`
- **Intervention Target**: `{spec.target_component}` (Layer {spec.layer}, {spec.component_type} #{spec.component_index})
- **Intervention Type**: `{spec.intervention_type}` (scale: {spec.ablation_scale})
- **Random Seed**: `{spec.random_seed}`

---

## 2. Model & Execution Environment
- **Model**: `{model.model_id}` ({model.architecture}, {model.parameter_count:,} params)
- **Weights SHA-256**: `{model.weights_hash}`
- **Python**: `{env.python_version}`
- **PyTorch**: `{env.pytorch_version}`
- **Transformers**: `{env.transformers_version}`
- **Platform**: `{env.os_platform} {env.os_release}`

---

## 3. Results & Provenance
- **Clean Logit**: `{meas.get('clean_logit')}` (Rank: `{meas.get('clean_rank')}`)
- **Intervened Logit**: `{meas.get('intervened_logit')}` (Rank: `{meas.get('intervened_rank')}`)
- **Measured Causal Effect ($\Delta z$)**: `{meas.get('delta_logit')}`
- **Evidence Level**: `{prov.final_evidence_tier}`
- **Verdict**: {run.verdict}

---

## 4. How to Reproduce Standalone
Run the enclosed self-contained script:
```bash
python reproduce.py
```
"""


class ArchiveBuilder:
    """Creates verifiable JSON packages and ZIP archives for immutable experiment runs."""

    @staticmethod
    def build_archive_dict(run: ImmutableExperimentRun) -> Dict[str, str]:
        """Builds all text contents and calculates manifest.json SHA-256 map."""
        exp_json = json.dumps(run.specification.to_dict(), indent=2)
        env_json = json.dumps(run.environment.to_dict(), indent=2)
        meas_json = json.dumps(run.measurements, indent=2)
        controls_json = json.dumps(run.provenance_chain.four_control_results, indent=2)
        null_json = json.dumps({
            "percentile": run.provenance_chain.null_distribution_percentile,
            "p_value": run.provenance_chain.null_distribution_p_value,
        }, indent=2)
        model_json = json.dumps(run.model.to_dict(), indent=2)
        reproduce_py = generate_standalone_reproduce_script(run)
        readme_md = generate_readme_md(run)

        manifest = {
            "archive_format": "MECH_EXPERIMENT_ARCHIVE_V1",
            "run_id": run.run_id,
            "experiment_type": run.experiment_type,
            "timestamp_utc": run.timestamp_utc,
            "files": {
                "experiment.json": _hash_str(exp_json),
                "environment.json": _hash_str(env_json),
                "measurements.json": _hash_str(meas_json),
                "controls.json": _hash_str(controls_json),
                "null_distribution.json": _hash_str(null_json),
                "model_manifest.json": _hash_str(model_json),
                "reproduce.py": _hash_str(reproduce_py),
                "README.md": _hash_str(readme_md),
            }
        }
        manifest_json = json.dumps(manifest, indent=2)

        return {
            "manifest.json": manifest_json,
            "experiment.json": exp_json,
            "environment.json": env_json,
            "measurements.json": meas_json,
            "controls.json": controls_json,
            "null_distribution.json": null_json,
            "model_manifest.json": model_json,
            "reproduce.py": reproduce_py,
            "README.md": readme_md,
        }

    @staticmethod
    def build_zip_bytes(run: ImmutableExperimentRun) -> bytes:
        """Packages the archive into an in-memory ZIP file."""
        files = ArchiveBuilder.build_archive_dict(run)
        buffer = BytesIO()
        with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
            for filename, content in files.items():
                zip_file.writestr(filename, content)
        buffer.seek(0)
        return buffer.getvalue()
