"""Autonomous Discovery Planner & Evidence Fusion Engine.

Elevates the platform from a toolbox of individual algorithms into an 
autonomous mechanistic research system.

Workflow:
Research Goal ➔ Discovery Planner ➔ Strategy & Pipeline Selection 
             ➔ Multi-Stage Algorithm Execution ➔ Evidence Fusion ➔ Mechanism Claim
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from backend.science.models.adapter_base import ModelAdapter
from .algorithms import get_algorithm
from .algorithms.base_algorithm import DiscoveryReport
from backend.research_datasets.dataset_manager import DatasetManager


@dataclass
class ResearchGoal:
    """High-level research objective specified by the researcher."""
    goal_id: str
    description: str
    model_id: str = "gpt2"
    dataset_name: str = "ioi"
    target_behavior: str = "logit_difference"
    require_falsification: bool = True
    require_universality: bool = False
    max_runtime_ms: float = 60000.0


@dataclass
class PipelineStage:
    """A single execution stage in a planned research campaign."""
    stage_number: int
    algorithm_name: str
    purpose: str
    config_override: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PipelinePlan:
    """The multi-stage execution strategy generated by the Discovery Planner."""
    goal_id: str
    stages: List[PipelineStage]
    rationale: str
    estimated_runtime_ms: float


@dataclass
class MechanismClaim:
    """The final scientific mechanism claim resulting from fused multi-algorithm evidence."""
    claim_id: str
    goal_description: str
    summary_claim: str
    #: Optional, and Optional for a reason. A campaign that measured nothing has
    #: no composite confidence; it previously reported 0.95 beside a fabricated
    #: IOI graph. `None` is also what a downstream gate must not read as a score.
    composite_confidence: Optional[float]
    evidence_chain: List[Dict[str, Any]]
    unified_graph: Dict[str, Any]
    #: `None` means no falsification was established -- either no stage ran, or
    #: the one that ran was unmeasured. That is not the same as `False`.
    falsification_passed: Optional[bool]
    runtime_ms: float
    timestamp: str = field(default_factory=lambda: _dt.datetime.utcnow().isoformat() + "Z")
    #: Whether `falsification_passed` is a claim about the hypothesis at all.
    falsification_established: bool = False
    falsification_reason: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "claim_id": self.claim_id,
            "goal_description": self.goal_description,
            "summary_claim": self.summary_claim,
            "composite_confidence": self.composite_confidence,
            "evidence_chain": self.evidence_chain,
            "unified_graph": self.unified_graph,
            "falsification_passed": self.falsification_passed,
            "falsification_established": self.falsification_established,
            "falsification_reason": self.falsification_reason,
            "runtime_ms": self.runtime_ms,
            "timestamp": self.timestamp,
        }


def _claim_id(goal_id: str) -> str:
    """A stable identifier for a claim.

    SHA-256 over the goal id and the timestamp, so the id identifies this run.
    `abs(hash(...))` was used before, which differs per interpreter process
    (Python salts string hashing) *and* per call because `time.time()` was in the
    input -- so no two runs produced the same id, and no id could be looked up.
    """
    payload = f"{goal_id}:{_dt.datetime.utcnow().isoformat()}"
    return "claim_" + hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


class AutonomousDiscoveryPlanner:
    """Autonomous engine that plans, sequences, executes, and fuses multi-algorithm research campaigns."""

    def __init__(self, adapter: Optional[ModelAdapter] = None, dataset_manager: Optional[DatasetManager] = None) -> None:
        self.adapter = adapter
        self.dataset_manager = dataset_manager or DatasetManager("backend/research_datasets")

    def plan(self, goal: ResearchGoal) -> PipelinePlan:
        """Analyzes a research goal and automatically builds an optimal multi-stage algorithm pipeline."""
        stages: List[PipelineStage] = []
        rationale_parts: List[str] = []

        desc_lower = goal.description.lower()
        stage_num = 1

        # Stage 1: Fast Screening via Attribution Patching
        stages.append(PipelineStage(
            stage_number=stage_num,
            algorithm_name="attribution_patching",
            purpose="Fast O(1) Taylor expansion screening to isolate high-attribution components."
        ))
        rationale_parts.append("1. Fast Attribution Patching screens all components in a single pass.")
        stage_num += 1

        # Stage 2: Subgraph Extraction (ACDC / Path Patching)
        if "path" in desc_lower or "edge" in desc_lower:
            stages.append(PipelineStage(
                stage_number=stage_num,
                algorithm_name="path_patching",
                purpose="Path Patching evaluates direct causal pathways between early senders and late receivers."
            ))
            rationale_parts.append("2. Path Patching validates direct causal edges between layers.")
        else:
            stages.append(PipelineStage(
                stage_number=stage_num,
                algorithm_name="acdc",
                purpose="ACDC iteratively prunes non-essential heads to extract the minimal circuit."
            ))
            rationale_parts.append("2. ACDC prunes non-essential nodes to isolate the minimal computational subgraph.")
        stage_num += 1

        # Stage 3: Rigorous Causal Falsification (Causal Scrubbing)
        if goal.require_falsification:
            stages.append(PipelineStage(
                stage_number=stage_num,
                algorithm_name="causal_scrubbing",
                purpose="Causal Scrubbing tests behavior preservation under equivalence class activation resamplings."
            ))
            rationale_parts.append("3. Causal Scrubbing validates hypothesis preservation under equivalence class resamplings.")
            stage_num += 1

        # Stage 4: Feature Representation & Universality (SAE / Transcoders / Universality)
        if "mlp" in desc_lower or "transcoder" in desc_lower:
            stages.append(PipelineStage(
                stage_number=stage_num,
                algorithm_name="transcoders",
                purpose="Transcoder Dictionary Learning decomposes non-linear MLP transformations into sparse features."
            ))
            rationale_parts.append("4. Transcoder dictionary learning transcode MLP non-linearities.")
            stage_num += 1

        if goal.require_universality or "universal" in desc_lower or "cross-model" in desc_lower:
            stages.append(PipelineStage(
                stage_number=stage_num,
                algorithm_name="feature_universality",
                purpose="Feature Universality matches sparse features across model architectures via bipartite alignment."
            ))
            rationale_parts.append("4. Feature Universality aligns concepts across model architectures.")
            stage_num += 1

        estimated_runtime = len(stages) * 8000.0  # Approx 8s per stage

        return PipelinePlan(
            goal_id=goal.goal_id,
            stages=stages,
            rationale=" ".join(rationale_parts),
            estimated_runtime_ms=estimated_runtime
        )

    def execute_campaign(self, goal: ResearchGoal) -> MechanismClaim:
        """Executes a planned research campaign end-to-end and fuses evidence into a Mechanism Claim."""
        t0 = time.time()
        plan = self.plan(goal)

        prompts = self.dataset_manager.load(goal.dataset_name)
        dataset_item = prompts[0] if prompts else {"clean": "John gave a drink to Mary", "target": " Mary"}

        reports: List[DiscoveryReport] = []
        evidence_chain: List[Dict[str, Any]] = []

        fused_nodes: List[Dict[str, Any]] = []
        fused_edges: List[Dict[str, Any]] = []
        seen_nodes = set()
        seen_edges = set()

        # Three states, not two.
        #
        # Was `falsification_passed = True` -- "falsification passed" was the
        # state before any falsification had run, so a campaign with no
        # causal-scrubbing stage at all reported a *passed* falsification and
        # had that sentence written into its summary.
        #
        #   None  no falsification stage ran, or the one that ran was unmeasured
        #   False falsification ran and the hypothesis did not survive it
        #   True  falsification ran and the hypothesis survived it
        #
        # Only the last two are a claim about the hypothesis.
        falsification_passed: Optional[bool] = None
        falsification_established = False
        falsification_reason = "No causal-scrubbing stage was planned or executed."

        # Execute each planned algorithm stage sequentially
        for stage in plan.stages:
            if not self.adapter:
                # Mock fallback report if no adapter connected
                continue

            alg_instance = get_algorithm(stage.algorithm_name, self.adapter)
            report = alg_instance.run(dataset_item)
            reports.append(report)

            # Check falsification result if Causal Scrubbing ran
            if stage.algorithm_name == "causal_scrubbing":
                # Was `report.statistics.get("validated", True)`. A causal-scrubbing
                # report that does not carry a `validated` key -- because the
                # stage was declined, incomplete, or unmeasured -- scored as a
                # PASSED falsification. Falsification is the one stage whose
                # silence should never be read as support: an unrun falsification
                # leaves the hypothesis untested, not upheld.
                falsification_passed = report.statistics.get("validated")
                if falsification_passed is None:
                    falsification_reason = (
                        "Causal scrubbing ran but reported no `validated` "
                        "verdict, so the hypothesis was not tested."
                    )
                elif falsification_passed:
                    falsification_established = True
                    falsification_reason = (
                        "Causal scrubbing ran and the hypothesis survived it."
                    )
                else:
                    falsification_established = True
                    falsification_reason = (
                        "Causal scrubbing ran and the hypothesis did not "
                        "survive it."
                    )

            evidence_chain.append({
                "stage": stage.stage_number,
                "algorithm": stage.algorithm_name,
                "purpose": stage.purpose,
                "confidence": report.confidence,
                "runtime_ms": report.runtime_ms,
                "statistics": report.statistics
            })

            # Merge graphs
            for node in report.graph.get("nodes", []):
                nid = node.get("id")
                if nid and nid not in seen_nodes:
                    seen_nodes.add(nid)
                    fused_nodes.append(node)

            for edge in report.graph.get("edges", []):
                esig = f"{edge.get('source')}->{edge.get('target')}"
                if esig not in seen_edges:
                    seen_edges.add(esig)
                    fused_edges.append(edge)

        # Fuse evidence into a composite confidence.
        #
        # This used to be a fabricated circuit. With no reports it returned
        # `composite_confidence = 0.95` alongside a complete three-node IOI graph
        # naming L9H9 as the Name Mover Head with edges at 0.92/0.95 and
        # confidences 0.95/0.98, and a summary beginning "Validated mechanism for".
        # A caller reading `composite_confidence` got 0.95 and a caller rendering
        # `unified_graph` drew a specific invented claim about a specific head --
        # the same defect already fixed in `circuit_discovery.discover_circuit`.
        #
        # An unrun pipeline has no evidence, so it reports no evidence: empty
        # graph, confidence None, and a reason. Same keys as a real claim, so
        # consumers need no special case.
        if reports:
            # An arithmetic mean of the per-stage confidences. The comment above
            # this block claimed a "weighted harmonic mean favoring causal
            # scrubbing & attribution agreement"; no weighting and no harmonic
            # mean was ever computed, so stages counted equally and a stage
            # reporting 0.0 could not be heard.
            #
            # Stages that measured nothing report `confidence is None` and are
            # excluded -- averaging None as 0.0 would penalise a stage for being
            # honest, and averaging them in as if measured would not.
            measured = [r.confidence for r in reports if r.confidence is not None]
            unmeasured = [r.algorithm for r in reports if r.confidence is None]

            if measured:
                composite_confidence = sum(measured) / len(measured)
                # Penalise only an *established* falsification failure. An absent
                # or unmeasured falsification is already excluded from `measured`
                # by leaving the stage's own confidence out of the mean; applying
                # the 0.3 penalty as well would charge the same omission twice.
                if falsification_established and not falsification_passed:
                    composite_confidence *= 0.3
            else:
                # Every stage ran and every one declined to state a confidence.
                # That is not a score of zero and it is not a score of 0.95.
                composite_confidence = None
                no_confidence_reason = (
                    f"No stage produced a confidence ({len(reports)} ran, "
                    f"all unmeasured). Nothing was measured, so there is no "
                    f"composite to report."
                )
        else:
            composite_confidence = None
            unmeasured = []
            no_confidence_reason = (
                "No algorithm produced a report, so this campaign measured "
                "nothing. There is no graph and no confidence to report."
            )

        runtime_ms = (time.time() - t0) * 1000

        if composite_confidence is None:
            summary = (
                f"No mechanism was established for '{goal.description}'. "
                f"Pipeline planned {len(plan.stages)} algorithms "
                f"({', '.join(s.algorithm_name for s in plan.stages)}) but "
                f"produced no measurements. {no_confidence_reason}"
            )
        else:
            if falsification_established:
                falsification_txt = ("passed" if falsification_passed
                                    else "FAILED")
            else:
                falsification_txt = "not established"
            summary = (
                f"Mechanism evidence assembled for '{goal.description}'. "
                f"Pipeline executed {len(plan.stages)} algorithms "
                f"({', '.join(s.algorithm_name for s in plan.stages)}). "
                f"Causal Falsification: {falsification_txt}. "
                f"Composite Confidence: {composite_confidence * 100:.1f}% "
                f"over {len(measured)} of {len(reports)} reporting stages."
            )
            if unmeasured:
                summary += (f" Not counted: {', '.join(unmeasured)} "
                            f"(no confidence reported).")
            if not falsification_established:
                summary += f" {falsification_reason}"

        return MechanismClaim(
            # SHA-256 over (goal_id, timestamp). Was
            # `hash(goal.goal_id + str(time.time())) & 0xffffffff`, so the id
            # differed on every interpreter start (Python salts string hashing
            # per process) *and* on every call -- an identifier that cannot
            # identify anything. Same fix as `live_discovery._discovery_id`.
            claim_id=_claim_id(goal.goal_id),
            goal_description=goal.description,
            summary_claim=summary,
            composite_confidence=(None if composite_confidence is None
                                  else round(composite_confidence, 4)),
            evidence_chain=evidence_chain,
            unified_graph={
                "nodes": fused_nodes,
                "edges": fused_edges,
                "score": (None if composite_confidence is None
                          else round(composite_confidence, 3)),
                "measured": composite_confidence is not None,
            },
            falsification_passed=falsification_passed,
            falsification_established=falsification_established,
            falsification_reason=falsification_reason,
            runtime_ms=runtime_ms
        )
